const fs = require('fs');
const path = require('path');
const axios = require('axios');
require('dotenv').config();

const HEVY_API_KEY = process.env.HEVY_API_KEY;
const DAILY_ROUTINE_ID = process.env.DAILY_ROUTINE_ID;

const WORKOUT_FILE = path.join(__dirname, 'data', 'workouts-30days.json');
const TEMPLATES_FILE = path.join(__dirname, 'data', 'exercise_templates.json');
const ROUTINES_FILE = path.join(__dirname, 'data', 'routines.json');

async function autoplan() {
  try {
    const exercises = JSON.parse(fs.readFileSync(TEMPLATES_FILE));
    const recentWorkouts = JSON.parse(fs.readFileSync(WORKOUT_FILE));
    const routines = JSON.parse(fs.readFileSync(ROUTINES_FILE));

    const allExercises = Object.values(exercises);
    const selectedExercises = allExercises.sort(() => 0.5 - Math.random()).slice(0, 5);

    const exerciseBlocks = selectedExercises.map((ex) => ({
      exercise_template_id: ex.id,
      supersets: [],
      rest_period: null,
      notes: null,
      sets: [
        { type: "warmup", weight: 0, reps: 10 },
        { type: "working", weight: 50, reps: 8 },
        { type: "working", weight: 50, reps: 8 },
      ],
    }));

    console.log("📋 Available routines:");
    routines.forEach(r => console.log(`- ${r.title}`));

    const routineId = DAILY_ROUTINE_ID || routines.find(r => r.title?.includes("CoachGPT"))?.id;
    if (!routineId) throw new Error("No routine ID found");

    console.log("➡️ Using routine ID:", routineId);

    const payload = {
      routine: {
        title: "CoachGPT",
        notes: "Autogenerated from last 30 workouts 📈",
        exercises: exerciseBlocks
      }
    };

    console.log("📦 Payload:", JSON.stringify(payload, null, 2));

    const response = await axios.put(
      `https://api.hevyapp.com/v1/routines/${routineId}`,
      payload,
      {
        headers: {
          'Content-Type': 'application/json',
          'api-key': HEVY_API_KEY
        }
      }
    );

    console.log("✅ Routine updated:", response.status);
  } catch (error) {
    console.error("❌ Error in autoplan:", error.response?.data || error.message || error);
  }
}

if (require.main === module) autoplan();
module.exports = autoplan;
